# Generated by Django 5.2 on 2025-05-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, default='51cb4225a2074bbd9d065f751ecc6492', max_length=64, null=True, unique=True),
        ),
    ]
